fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
  symlinks:
    setroubleshoot: "#{source_dir}"
